# Generated by Django 2.2.2 on 2019-06-15 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinhos', '0002_auto_20190614_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinho',
            name='short_description',
            field=models.CharField(default='A dhasu dhasu dhasu hdasu hdasuh dusah duash udsah udsah udash udash', max_length=75),
            preserve_default=False,
        ),
    ]
