# Generated by Django 2.2.2 on 2019-06-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinhos', '0009_auto_20190614_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinho',
            name='picture',
            field=models.ImageField(upload_to='\\/vinhos_imagens', verbose_name='Imagem: '),
        ),
    ]
