# Generated by Django 2.2.2 on 2019-06-18 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinhos', '0014_auto_20190617_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinho',
            name='price',
            field=models.FloatField(default=50),
            preserve_default=False,
        ),
    ]
