# Generated by Django 2.2.2 on 2019-06-15 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinhos', '0004_auto_20190614_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vinho',
            name='category',
        ),
    ]
