# Generated by Django 2.2.2 on 2019-06-15 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinhos', '0006_delete_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinho',
            name='category',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
