# Generated by Django 2.2.2 on 2019-06-15 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinhos', '0007_vinho_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vinho',
            name='category',
        ),
    ]
