# Generated by Django 2.2.2 on 2019-06-17 23:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vinhos', '0010_auto_20190614_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='vinho',
            name='picture',
            field=models.ImageField(upload_to='vinhos_imagens', verbose_name='Imagem: '),
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=datetime.datetime(2019, 6, 17, 23, 41, 45, 869412, tzinfo=utc))),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinhos.Cliente')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinhos.Vinho')),
            ],
        ),
    ]
