# Generated by Django 2.2.2 on 2019-06-17 23:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vinhos', '0011_auto_20190617_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
