# Generated by Django 2.2.2 on 2019-06-17 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinhos', '0012_auto_20190617_2042'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Market',
            new_name='Carrinho',
        ),
    ]
