# Generated by Django 2.2.2 on 2019-06-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinhos', '0013_auto_20190617_2043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='cliente',
            name='carrinho',
            field=models.ManyToManyField(to='vinhos.Vinho'),
        ),
        migrations.DeleteModel(
            name='Carrinho',
        ),
    ]
